version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: "Build using Maven"
          command: |
            mvn -B -Dmaven.compile-native-executable.skip=true clean package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
